steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/iep-advocacy-platform:$BUILD_ID', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/iep-advocacy-platform:$BUILD_ID']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'iep-advocacy-platform'
      - '--image'
      - 'gcr.io/$PROJECT_ID/iep-advocacy-platform:$BUILD_ID'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--port'
      - '5000'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'NODE_ENV=production,REPLIT_DEPLOYMENT=1'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '300'
      - '--concurrency'
      - '80'

images:
  - 'gcr.io/$PROJECT_ID/iep-advocacy-platform:$BUILD_ID'