# Replit deployment configuration with fixed build process
[build]
command = "export PATH='/nix/store/hdq16s6vq9smhmcyl4ipmwfp9f2558rc-nodejs-20.10.0/bin:$PATH' && node build-deploy.js"

[run]
command = "./start-deployment.sh"

[env]
NODE_ENV = "production"
PORT = "5000"