[deployment]
build = "export PATH='/nix/store/hdq16s6vq9smhmcyl4ipmwfp9f2558rc-nodejs-20.10.0/bin:$PATH' && node build-deploy.js"
run = "./start-deployment.sh"

[deployment.env]
NODE_ENV = "production"
PORT = "5000"
REPLIT_DEPLOYMENT = "1"